apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-alertconfig
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- (.Files.Glob "alert_payload_templates/*").AsConfig | nindent 2 }}
  alertconfig.json: |
    {{ mustToJson .Values.alerting | nindent 4 }}